language: node_js
node_js:
  - "0.10"
before_install:
  - npm install coffee-script
  - npm install grunt-cli
  - npm install mocha
before_script:
  - coffee -c -o test test
  - rm test/data.coffee test/segmentSpec.coffee test/xmlSpec.coffee